verseion: "3.7"
services:
  zero9-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zero9-client
    restart: always
    ports:
      - 3000:3000
    environment:
      - TZ=Asia/Seoul
